name: Elixir tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13.4
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PG_HOST: localhost
      PG_USERNAME: postgres
      PG_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.12.3" # Define the elixir version [required]
          otp-version: "24.1" # Define the OTP version [required]

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-build

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile
          mix ecto.create && mix ecto.migrate

      - name: Run tests
        run: mix test
